name: "Release"

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  docker-release:
    name: "Docker Release"
    uses: na4ma4/actions/.github/workflows/docker-release.yml@main
    secrets:
      DOCKER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      image: ghcr.io/na4ma4/website-na4ma4.com
      platforms: linux/amd64,linux/arm64
      semver-tag: true
